server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  
    url: jdbc:mysql://localhost:3306/microservices2
    username: root
    password: root
  jpa: 
    hibernate:
      ddl-auto: update
    show-sql: true
  
  logging:
  level:
    org.hibernate.dialect.Dialect: ERROR
